import generated from './records.generated.json'

/** A record in the crate (spec §4). Generated by `npm run content:records`
 *  from content/records.json; edit that file, not the generated one. */
export interface Track {
  id: string
  artist: string
  song: string
  album: string
  previewUrl: string
  appleMusicUrl: string
  /** Pixel album art under /public. */
  art: string
}

export const RECORDS: readonly Track[] = generated
