import {
  ACTIVE_DAYS_PER_YEAR,
  CPM_DESIGN_POINT,
  IMPRESSIONS_PER_USER_DAY,
  USER_REVENUE_SHARE,
} from './figures'

export interface PayoutInput {
  impressionsPerDay: number
  activeDays: number
  cpm: number
  share: number
}

export const DEFAULT_PAYOUT_INPUT: PayoutInput = {
  impressionsPerDay: IMPRESSIONS_PER_USER_DAY.value,
  activeDays: ACTIVE_DAYS_PER_YEAR.value,
  cpm: CPM_DESIGN_POINT.value,
  share: USER_REVENUE_SHARE.value,
}

/** Gross media value generated by one user in a year, in dollars. */
export function grossPerYear(
  impressionsPerDay: number,
  activeDays: number,
  cpm: number,
): number {
  return (impressionsPerDay * activeDays * cpm) / 1000
}

/**
 * What one impression clears for, in dollars. CPM is a price per thousand,
 * so this is simply CPM / 1000 — but it is a business figure, and business
 * figures live here rather than as a literal in a scene constant.
 */
export function pricePerImpression(cpm: number = CPM_DESIGN_POINT.value): number {
  return cpm / 1000
}

/**
 * Per-impression prices always render to three decimals. At every CPM this
 * market plausibly touches the price is a fraction of a cent, and the site's
 * usual two-decimal currency rule destroys it: the $25.00 design point's
 * $0.025 rounds up to $0.03 — a 20% overstatement — and the $2.80 observed
 * CPM's $0.0028 rounds to $0.00. The rule belongs here, next to the figure
 * it protects, not in whichever component happens to display it.
 */
export function formatPricePerImpression(price: number): string {
  return `$${price.toFixed(3)}`
}

/** What the user receives per month, in dollars of AI credit. */
export function userPayoutPerMonth(input: Partial<PayoutInput> = {}): number {
  const { impressionsPerDay, activeDays, cpm, share } = {
    ...DEFAULT_PAYOUT_INPUT,
    ...input,
  }
  return (grossPerYear(impressionsPerDay, activeDays, cpm) * share) / 12
}
